spring:
  logging:
    level: DEBUG
  graphql:
    cors:
      allow-credentials: true
      allowed-origins:
        - http://localhost:8000
    servlet:
      corsEnabled: true
    graphiql:
      enabled: true
  data:
    mongodb:
      host: akhilmongodbcluster.1iwfqix.mongodb.net/
      database: AkhilMongoDBDatabase
      username: xx
      password: xx
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: xx
        credential:
          client-id: xx
          client-secret: xx
        authorization-clients:
          azuredatabricks:
            scopes: 2ff814a6-3304-4ab8-85cb-cd0e6f879c1d/.default

graphql:
  servlet:
    enabled: true
    graphiql:
      enabled: true