spring:
  data:
    mongodb:
      host: xx
      database: xx
      username: xx
      password: xx
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: xx
        credential:
          client-id: xx
          client-secret: xx
        authorization-clients:
          azuredatabricks:
            scopes: xx