spring:
  logging:
    level: DEBUG
  graphql:
    cors:
      allow-credentials: true
      allowed-origins:
        - http://localhost:8000
    servlet:
      corsEnabled: true
    graphiql:
      enabled: true
  data:
    mongodb:
      uri: mongodb+srv://${mongodb-username}:${mongodb-password}@akhilmongodbcluster.1iwfqix.mongodb.net/AkhilMongoDBDatabase
  cloud:
    azure:
      keyvault:
        secret:
          property-source-enabled: true
          property-sources[0]:
            profile:
              tenant-id: ${spring.cloud.azure.active-directory.profile.tenant-id}
            credential:
              client-id: ${spring.cloud.azure.active-directory.credential.client-id}
              client-secret: ${spring.cloud.azure.active-directory.credential.client-secret}
            endpoint: https://akhil-mongodb-vault.vault.azure.net/
      active-directory:
        enabled: true
        profile:
          tenant-id: xx
        credential:
          client-id: xx
          client-secret: xx
        authorization-clients:
          azuredatabricks:
            scopes: 2ff814a6-3304-4ab8-85cb-cd0e6f879c1d/.default

graphql:
  servlet:
    enabled: true
    graphiql:
      enabled: true